### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by YoushaaMurhij** [OuyangJunyuan/pointcloud-3d-detector-tensorrt#1]
Hi! 
Thanks for sharing this great work!
I wonder if you plan to add ONNX and configs for models trained on other datasets (Waymo, nuScenes,...). If not, will you provide torch to onnx conversion script for IA-SSD?

Thanks

**Comment by OuyangJunyuan** [comment]
The code is still being cleaned up. We will release the PyTorch model and export scripts later today.

**Comment by YoushaaMurhij** [comment]
Thanks for your response!
